### ISSUE TITLE
Companion cannot connect to Tapo Smart Bulb

### ISSUE THREAD

**Issue by Dimholdt** [bitfocus/companion-module-tplink-taposmartplug#11]
Cannot connect to Smart Bulb model TL135. Firmware version is 1.0.5 Build 230627 Rel. 152735.

![image](https://github.com/bitfocus/companion-module-tplink-taposmartplug/assets/152247129/e274bc9d-5b63-4229-bea0-4bd8a9627845)

Here is the log. (not much here)

debug: Only recent lines are shown here, nothing is persisted
system: ** Log cleared **
system: ** Starting Connection from "C:\Program Files\Companion\resources\bundled-modules\tplink-taposmartplug\main.js" **
system: ** Connection started **
Starting up module class: 
Sentry disabled
Module-host accepted registration
error: Stopping Update interval due to error.
info: Stopping Update Interval.

**Comment by josephdadams** [comment]
I've just pushed `v2.0.2` of the module to the betas. Would you be able to try that and post your logs here? I'm curious if it is the same issue I am tracking with another user.

**Comment by Dimholdt** [comment]
Still not working with the latest beta. I have attached the logs
[companion_log_20240315-1729.csv](https://github.com/bitfocus/companion-module-tplink-taposmartplug/files/14621293/companion_log_20240315-1729.csv)

**Comment by josephdadams** [comment]
Looks like the same error I’m seeing in other installs.

https://github.com/dickydoouk/tp-link-tapo-connect/issues/44

Oddly enough it’s working just fine on mine.

**Comment by Dimholdt** [comment]
I have a few of the smart plugs model TP15. These all work fine. 
I also have the outdoor smart plug TP25. It can connect just fine but I cannot control either of the two plugs.
The issue is limited to the smart bulbs on my network. If there is anything I can do on my side to help troubleshoot, please let me know.
